name: build-test-deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build
  # Test will execute after build completes successfully
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm test
  deploy:
    needs: test
    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
       token: ${{ secrets.GITHUB_TOKEN }} # needs token as will be doing writing in deploy step
    - name: Use node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: configure github pages
      uses: actions/configure-pages@v4
      with:
        static_site_generator: next # ensure setup correctly for next.js project
    - run: npm install
    - run: npm run build
    - name: upload artifacts
      uses: actions/upload-pages-artifact@v3
      with:
       path: './out' # wraps up our directory artifacts and sends to pages for deployment
    - name: deploy
      id: deployment # to be able to keep an eye on deployment status
      uses: actions/deploy-pages@v4
